# compose versions are no longer needed for Compose CLI

services:

  traefik:
    image: traefik:1.7-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    command:
      - --docker
      - --docker.domain=traefik
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.localhost
    networks:
      - frontend
      - backend


  redis:
    image: redis:alpine
    networks:
      - frontend
    healthcheck:
      test: redis-cli ping

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres || exit 1

  vote:
    image: bretfisher/examplevotingapp_vote
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:vote.localhost
    ports:
      - '5000:80'
    networks:
      - frontend
    depends_on:
      redis:
        condition: service_healthy


  result:
    build:
      context: result
    command: nodemon --inspect=0.0.0:9229 server.js
    environment:
      - NODE_ENV=development
    volumes:
      - ./result:/app
    networks:
      - backend
    ports:
      - '5001:80'
      - '9229:9229'
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:result.localhost

  worker:
    image: bretfisher/examplevotingapp_worker:stable-20240415-f296469
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  frontend:
  backend:

volumes:
  db-data:
